require 'active_support/all'
require 'faraday'
require 'faraday_middleware'

require 'avatax/version'
require 'avatax/code'

require 'avatax/api/base'
require 'avatax/api/accounts'
require 'avatax/api/addresses'
require 'avatax/api/batches'
require 'avatax/api/companies'
require 'avatax/api/contacts'
require 'avatax/api/definitions'
require 'avatax/api/items'
require 'avatax/api/locations'
require 'avatax/api/nexus'
require 'avatax/api/settings'
require 'avatax/api/subscriptions'
require 'avatax/api/tax_codes'
require 'avatax/api/tax_rates'
require 'avatax/api/tax_rules'
require 'avatax/api/transactions'
require 'avatax/api/upcs'
require 'avatax/api/users'
require 'avatax/api/utilities'

require 'avatax/configuration'
require 'avatax/client'
